# Aula 15 - Algoritmos e Estrutura de Dados 
## Exercícios sobre Numpy

## Fácil

⚫1- Importe numpy como ‘np’ e imprima o número da versão.

In [1]:
import numpy as np 
print (np.__version__)

1.26.4


⚫2- Crie uma matriz 1D com números de 0 a 9

In [3]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


⚫3- Crie uma matriz booleana numpy 3×3 com ‘True’

In [9]:
array1 = np.array([[2,4,6],[2,4,6],[2,4,6]])
mascara = (array1 % 2 == 0)
print(array1)

[[2 4 6]
 [2 4 6]
 [2 4 6]]


In [10]:
print(mascara)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


⚫4- Extraia todos os números ímpares de ‘arr’

In [29]:
import numpy as np

array2 = np.array([0,1,2,3,4,5,6,7,8,9])
numeros_impares = [array2 % 2 == 1]
print(numeros_impares)

[array([False,  True, False,  True, False,  True, False,  True, False,
        True])]


⚫5- Substitua todos os números ímpares arr por -1

In [20]:
array[array % 2 == 1] = -1
print(array)

[-1  2 -1  4 -1  6 -1  8 -1]


## Médio

⚫1- Substitua todos os números ímpares em arr com -1 sem alterar arr

⚫2- Converta uma matriz 1D para uma matriz 2D com 2 linhas:

⚫3- Empilhe matrizes verticalmente:

⚫4- Empilhe as matrizes horizontalmente:

⚫5- Crie o seguinte padrão sem codificação, usando apenas funções numpy e a matriz de entrada abaixo ‘a’.

In [ ]:
a = np.array([1,2,3])

## Difícil 

⚫1- Calcule as contagens de valores únicos na linha.

In [ ]:
import numpy as np
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)

In [ ]:
def counts_of_all_values_rowwise(arr2d):
