# Aula 15 - Algoritmos e Estrutura de Dados 
## Exercícios sobre Numpy

## Fácil

⚫1- Importe numpy como ‘np’ e imprima o número da versão.

In [1]:
import numpy as np 
print (np.__version__)

1.26.4


⚫2- Crie uma matriz 1D com números de 0 a 9

In [3]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


⚫3- Crie uma matriz booleana numpy 3×3 com ‘True’

In [9]:
array1 = np.array([[2,4,6],[2,4,6],[2,4,6]])
mascara = (array1 % 2 == 0)
print(array1)

[[2 4 6]
 [2 4 6]
 [2 4 6]]


In [10]:
print(mascara)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


⚫4- Extraia todos os números ímpares de ‘arr’

In [2]:
import numpy as np

array2 = np.array([0,1,2,3,4,5,6,7,8,9])
numeros_impares = array2[array2 % 2 == 1]
print(numeros_impares)

[1 3 5 7 9]


⚫5- Substitua todos os números ímpares arr por -1

In [20]:
array[array % 2 == 1] = -1
print(array)

[-1  2 -1  4 -1  6 -1  8 -1]


## Médio

⚫1- Substitua todos os números ímpares em arr com -1 sem alterar arr

In [19]:
import numpy as np

array2 = np.arange(10)
array_copy = np.copy(array2)
array_copy[array_copy % 2 == 1] = -1

print("Array original:", array2)
print("Array com números ímpares substituídos:", array_copy)

Array original: [0 1 2 3 4 5 6 7 8 9]
Array com números ímpares substituídos: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


⚫2- Converta uma matriz 1D para uma matriz 2D com 2 linhas:

In [25]:
import numpy as np

array3 = np.arange(6)
print(array3)
array3.reshape(2, -1)

[0 1 2 3 4 5]


array([[0, 1, 2],
       [3, 4, 5]])

⚫3- Empilhe matrizes verticalmente:

In [27]:
import numpy as np

matriz1 = np.array([[1, 2, 3], [4, 5, 6]])
matriz2 = np.array([[7, 8, 9], [10, 11, 12]])
matrizes_empilhadas = np.vstack((matriz1, matriz2))

print("Matriz 1:")
print(matriz1)
print("Matriz 2:")
print(matriz2)
print("Matrizes empilhadas verticalmente:")
print(matrizes_empilhadas)

Matriz 1:
[[1 2 3]
 [4 5 6]]
Matriz 2:
[[ 7  8  9]
 [10 11 12]]
Matrizes empilhadas verticalmente:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


⚫4- Empilhe as matrizes horizontalmente:

In [28]:
matriz1 = np.array([[1, 2, 3], [4, 5, 6]])
matriz2 = np.array([[7, 8, 9], [10, 11, 12]])
matrizes_empilhadas = np.hstack((matriz1, matriz2))
print("Matrizes empilhadas verticalmente:")
print(matrizes_empilhadas)

Matrizes empilhadas verticalmente:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


⚫5- Crie o seguinte padrão sem codificação, usando apenas funções numpy e a matriz de entrada abaixo ‘a’.

In [30]:
a = np.array([1,2,3])

In [31]:
import numpy as np
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## Difícil 

⚫1- Calcule as contagens de valores únicos na linha.

In [3]:
import numpy as np
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)

[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]


In [5]:
import numpy as np

def contar_valores_unicos_linha(linha):
    valores_unicos, contagens = np.unique(linha, return_counts=True)
    return dict(zip(valores_unicos, contagens))

contagens_por_linha = np.apply_along_axis(contar_valores_unicos_linha, axis=1, arr=arr)
print(contagens_por_linha)

[{1: 1, 3: 2, 4: 1, 5: 1, 6: 1, 8: 2, 9: 2}
 {1: 2, 2: 1, 3: 3, 5: 1, 7: 1, 9: 1, 10: 1}
 {2: 3, 4: 2, 5: 3, 6: 1, 8: 1}
 {1: 1, 3: 2, 4: 1, 6: 1, 8: 2, 9: 1, 10: 2}
 {1: 2, 2: 2, 3: 2, 6: 1, 7: 1, 8: 1, 9: 1}
 {1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 2, 9: 2, 10: 1}]
